import pytest

from words import words


@pytest.mark.wordinfo
def test_count_vowels(word_info_obj):
    assert word_info_obj.count_vowels() == {'Computer': 3, 'programming': 3, 'is': 1, 'the': 1, 'process': 2, 'of': 1, 'performing': 3, 'a': 1, 'particular': 4, 'computation': 5, 'or': 1, 'more': 2, 'generally': 3, 'accomplishing': 4, 'specific': 3, 'computing': 3, 'result': 2, 'usually': 3, 'by': 0, 'designing': 3, 'and': 1, 'building': 3, 'an': 1, 'executable': 5, 'computer': 3, 'program': 2, 'Programming': 3, 'involves': 3, 'tasks': 1, 'such': 1, 'as': 1, 'analysis': 3, 'generating': 4, 'algorithms': 3, 'profiling': 3, 'accuracy': 3, 'resource': 4, 'consumption': 4, 'implementation': 6, 'in': 1, 'chosen': 2, 'language': 4, 'commonly': 2, 'referred': 3, 'to': 1, 'coding': 2, 'The': 1, 'source': 3, 'code': 2, 'written': 2, 'one': 2, 'languages': 4, 'that': 1, 'are': 2, 'intelligible': 5, 'programmers': 3, 'rather': 2, 'than': 1, 'machine': 3, 'which': 1, 'directly': 2, 'executed': 4, 'central': 2, 'processing': 3, 'unit': 2, 'purpose': 3, 'find': 1, 'sequence': 4,
                                            'instructions': 4, 'will': 1, 'automate': 5, 'performance': 4, 'task': 1, 'can': 1, 'be': 1, 'complex': 2, 'operating': 4, 'system': 1, 'on': 1, 'often': 2, 'for': 1, 'solving': 2, 'given': 2, 'problem': 2, 'Proficient': 4, 'thus': 1, 'requires': 4, 'expertise': 4, 'several': 3, 'different': 3, 'subjects': 2, 'including': 3, 'knowledge': 3, 'application': 5, 'domain': 3, 'specialized': 5, 'formal': 2, 'logic': 2, 'Tasks': 1, 'accompanying': 4, 'related': 3, 'include': 3, 'testing': 2, 'debugging': 3, 'maintenance': 5, 'build': 2, 'systems': 1, 'management': 4, 'derived': 3, 'artifacts': 3, 'programs': 2, 'These': 2, 'might': 1, 'considered': 4, 'part': 1, 'but': 1, 'term': 1, 'software': 3, 'development': 4, 'used': 2, 'this': 1, 'larger': 2, 'with': 1, 'reserved': 3, 'actual': 3, 'writing': 2, 'Software': 3, 'engineering': 5, 'combines': 3, 'techniques': 4, 'practices': 3, 'Reverse': 3, 'designers': 3, 'analysts': 2, 'understand': 3, 'recreatereimplement': 8}


@pytest.mark.wordinfo
def test_count_consonants(word_info_obj):
    assert word_info_obj.count_consonants() == {'Computer': 5, 'programming': 8, 'is': 1, 'the': 2, 'process': 5, 'of': 1, 'performing': 7, 'a': 0, 'particular': 6, 'computation': 6, 'or': 1, 'more': 2, 'generally': 6, 'accomplishing': 9, 'specific': 5, 'computing': 6, 'result': 4, 'usually': 4, 'by': 2, 'designing': 6, 'and': 2, 'building': 5, 'an': 1, 'executable': 5, 'computer': 5, 'program': 5, 'Programming': 8, 'involves': 5, 'tasks': 4, 'such': 3, 'as': 1, 'analysis': 5, 'generating': 6, 'algorithms': 7, 'profiling': 6, 'accuracy': 5, 'resource': 4, 'consumption': 7, 'implementation': 8, 'in': 1, 'chosen': 4, 'language': 4, 'commonly': 6, 'referred': 5, 'to': 1, 'coding': 4, 'The': 2, 'source': 3, 'code': 2, 'written': 5, 'one': 1, 'languages': 5, 'that': 3, 'are': 1, 'intelligible': 7, 'programmers': 8, 'rather': 4, 'than': 3, 'machine': 4, 'which': 4, 'directly': 6, 'executed': 4, 'central': 5, 'processing': 7, 'unit': 2, 'purpose': 4, 'find': 3, 'sequence': 4,
                                                'instructions': 8, 'will': 3, 'automate': 3, 'performance': 7, 'task': 3, 'can': 2, 'be': 1, 'complex': 5, 'operating': 5, 'system': 5, 'on': 1, 'often': 3, 'for': 2, 'solving': 5, 'given': 3, 'problem': 5, 'Proficient': 6, 'thus': 3, 'requires': 4, 'expertise': 5, 'several': 4, 'different': 6, 'subjects': 6, 'including': 6, 'knowledge': 6, 'application': 6, 'domain': 3, 'specialized': 6, 'formal': 4, 'logic': 3, 'Tasks': 4, 'accompanying': 8, 'related': 4, 'include': 4, 'testing': 5, 'debugging': 6, 'maintenance': 6, 'build': 3, 'systems': 6, 'management': 6, 'derived': 4, 'artifacts': 6, 'programs': 6, 'These': 3, 'might': 4, 'considered': 6, 'part': 3, 'but': 2, 'term': 3, 'software': 5, 'development': 7, 'used': 2, 'this': 3, 'larger': 4, 'with': 3, 'reserved': 5, 'actual': 3, 'writing': 5, 'Software': 5, 'engineering': 6, 'combines': 5, 'techniques': 6, 'practices': 6, 'Reverse': 4, 'designers': 6, 'analysts': 6, 'understand': 7, 'recreatereimplement': 11}
